apiVersion: v1
kind: Pod
metadata:
  name: yellow
  labels:
    name: yellow
spec:
  containers:
    - name: lemon
      imagePullPolicy: Always
      image:  busybox
    - name: gold
      imagePullPolicy: Always
      image:  redis
