apiVersion: v1
kind: Pod
metadata:
  name: bee
  labels:
    name: bee
spec:
  containers:
    - name: wbee
      imagePullPolicy: Always
      image:  nginx
  tolerations:
    - key: "spray"
      operator: "Equal"
      value: "mortein"
      effect: "NoSchedule"
