apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  labels:
    name: webapp-color
spec:
  containers:
    - name: webapp-color
      imagePullPolicy: Always
      image: kodekloud/webapp-color
      # whole resource
      envFrom:
        - secretRef:
            name: app-secret 
      # the single variable
      env:
        - name: DB_Password
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_Password