apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    name: webapp-pod
spec:
  containers:
    - name: webapp-pod
      imagePullPolicy: Always
      image:  kodekloud/simple-webapp-mysql
      envFrom:
        - secretRef:
            name: db-secret