apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  labels:
    name: ubuntu-sleeper
spec:
  containers:
    - name: ubuntu-sleeper
      imagePullPolicy: Always
      image:  ubuntu
      command: ["sleep", "4800"]
      securityContext:
        capabilities:
          add: ["SYS_TIME"]