apiVersion: v1
kind: Pod
metadata:
	name: webapp-color
	labels:
		name: webapp-color
spec:
	containers:
		- name: webapp-color
		  imagePullPolicy: Always
		  image: kodekloud/webapp-color
		  configMapRef:
		  	name: webapp-config-map